### ISSUE TITLE
Remove latex cruft

### ISSUE THREAD

**Issue by timj** [lsst-dm/dmtn-065#1]
Please remove the latex cruft from the repository (.log, .out etc). Consider asking github to put in a latex `.gitignore` file when creating the repository in future.

**Comment by jdswinbank** [comment]
These files were removed [long ago](https://github.com/lsst-dm/dmtn-065/commit/05620573d5c44d5b5f37c9c49bd9423bcd612204#diff-a084b794bc0759e7a6b77810e01874f2).
