### ISSUE TITLE
can not write to repo

### ISSUE THREAD

**Issue by womullan** [lsst-dm/dmtn-065#2]
I have made the tex fixes but I am not allowed to make a branch on your repo to make a pull request .. that seems odd. 
This is a DMNT should probably be with the other DMTNs under  LSST-DM  so it shows up int he list of DMTNs and you should claim the next number for it .

**Comment by mjuric** [comment]
Hi @womullan -- you have an invitation pending from this organization; if you accept it it will let you commit.

**Comment by mjuric** [comment]
@MelissaGraham, let's move the repository to lsst-dm organization.

**Comment by womullan** [comment]
I do not see an invite - still can not write. Shall i move this ?

**Comment by MelissaGraham** [comment]
This can be moved to anywhere as needed -- just tell me where or go ahead and move it and point me to its new home?

**Comment by jdswinbank** [comment]
Obsolete; closing.
